### PR TITLE
Add capability to build using docker containers

### PR DESCRIPTION
**Pull request by dangogh**
This is an experimental feature,  but expected to be used to help set up continuous integration as well as help make development environments consistent.

Docker setup is capable of pulling from any fork and/or branch; defaults to Comcast/traffic_control and master.

### CODE REVIEW

**Comment by mitchell852** [comment]
want an unsolicited feature request? it would probably be a nice option to have a `-t` flag to pass in the tag or release to build...

**Comment by dangogh** [comment]
-b option can be used to specify either branch or tag.   Maybe that needs to be made more clear...

**Comment by mitchell852** [comment]
keeping the docker images seems to be causing a problem. i did this

`./docker-build.sh -b RELEASE-1.6.0-RC4`

and ended up with traffic_ops-1.7.0-3578.6400007c.x86_64.rpm

**Comment by dangogh** [comment]
yep..  gitter container left around.  That needs to be recreated from the image.  Update coming shortly.

**Pull request merged**
