### PR TITLE
added port to drop_qstring.config of ATS

### LINKED ISSUE #259: Drop querystring doesn't work when there is a port specified in the org server base url.

### PR DESCRIPTION
**Pull request by hbeatty**
1. traffic_ops/app/lib/UI/ConfigFiles.pm - drop_qstring_dot_config()
add $p (port) to $text.

closes #259

### CODE REVIEW

**Comment by knutsel** [comment]
ATS docs say

$p     - The original port number

don't they mean the port number of the left-hand-side of the remap line with that? We need a solution for when the right-hand-side of the remap line (the origin) has a port number specified?

**Comment by smalenfant** [comment]
Jan, for some reason we tested this and it works. But I tested on a system
with no Mid-Cache so let us confirm Monday. Without this setting, the curl
would just hang because the origin isn't listening on port 80.

curl
http://devscdedge03.vod.devs.cdn.coxlab.net/devLg/ImportPath/HardLinks/49/5A/adipp-comedycentral.com-AFEM0000000000318709/adi11_comedycentral.com_AFEM0000000000318709/1250/00000100.ts
-o /dev/null -v

1436614821.088 chi=2001:578:30:5618:174:68:247:250 phn=
devscdedge03.coxlab.net shn=pve-origin.services.coxlab.net url=
http://devscdedge03.vod.devs.cdn.coxlab.net/devLg/ImportPath/HardLinks/49/5A/adipp-comedycentral.com-AFEM0000000000318709/adi11_comedycentral.com_AFEM0000000000318709/1250/0000000F.ts
cqhm=GET cqhv=HTTP/1.1 pssc=200 ttms=1 b=217520 sssc=000 sscl=0 cfsc=FIN
pfsc=FIN crc=TCP_HIT phr=NONE uas="curl/7.19.7 (x86_64-redhat-linux-gnu)
libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"


[root@devscdedge03 trafficserver]# netstat -an | grep 8081

tcp        0      0 174.68.247.250:37990        10.8.180.93:8081
ESTABLISHED

Remap :

map http://devscdedge03.vod.devs.cdn.coxlab.net/
http://pve-origin.services.coxlab.net:8081/ @plugin=header_rewrite.so
@pparam=dscp/set_dscp_0.config @plugin=regex_remap.so
@pparam=drop_qstring.config


[root@devscdedge03 trafficserver]# cat
/opt/trafficserver/etc/trafficserver/drop_qstring.config

# DO NOT EDIT - Generated for devscdedge03 by Traffic Ops (
https://tm.kabletown.net/) on Thu Jul  9 18:45:50 UTC 2015

#/([^?]+) $s://$t/$1

/([^?]+) $s://$t:$p/$1


Reverting back, request gets hung :

[root@devscdedge03 trafficserver]# curl
http://devscdedge03.vod.devs.cdn.coxlab.net/devLg/ImportPath/HardLinks/49/5A/adipp-comedycentral.com-AFEM0000000000318709/adi11_comedycentral.com_AFEM0000000000318709/1250/00000101.ts
-o /dev/null -v

* About to connect() to devscdedge03.vod.devs.cdn.coxlab.net port 80 (#0)

*   Trying 2001:578:30:5618:174:68:247:250... connected

* Connected to devscdedge03.vod.devs.cdn.coxlab.net
(2001:578:30:5618:174:68:247:250) port 80 (#0)

> GET
/devLg/ImportPath/HardLinks/49/5A/adipp-comedycentral.com-AFEM0000000000318709/adi11_comedycentral.com_AFEM0000000000318709/1250/00000101.ts
HTTP/1.1

> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/
3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2

> Host: devscdedge03.vod.devs.cdn.coxlab.net

> Accept: */*

>

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current

                                 Dload  Upload   Total   Spent    Left
Speed

  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--
  0^C

**Comment by dneuman64** [comment]
Hey @smalenfant any updates on this?  Sounds like you were gonna do some testing and get back to us.

**Comment by smalenfant** [comment]
We've been using ```/([^?]+) $s://$t:$p/$1``` in the drop_qstring.config for a while now. Didn't see any problems. This means this takes care of "2 - Drop At Edge". Although @mtorluemke might want this to go as a string in the Traffic Ops DB and then generated based on that string.

This fix is required for us at this time. But unsure if it can accepted as-is for now.

What I believe would need to be done :

- Add parameter "drop_qstring", Config file name "drop_qstring.config" with value "/([^?]+) $s://$t:$p/$1"
- Change Traffic Ops config generation code using the value instead of being hard coded.
- Modify ORT to verify if drop_qstring has been changed

Comments?

**Comment by mtorluemke** [comment]
Hmm...the regex_remap code seems to confirm that it is the request URL (left side of remap line):

From regex_remap.cc:

 581         case SUB_PORT:
 582           p1 += snprintf(p1, 6, "%u", req_url->port);
 583           break;

Line numbers above are from tip of 5.3.x branch. I'll setup a test to replicate yours.

**Comment by mtorluemke** [comment]
A test confirms what the code says, but there is a problem here. I setup my remap.config line like this:

```map	http://<test-cache-1.kabletown.net>/     http://<origin-server-1.kabletown.net>:81/ @plugin=regex_remap.so @pparam=drop_qstring.config```

Then, in error.log, with the existing drop_qstring.config, I see:

```20150827.20h39m49s RESPONSE: sent <xxx.xxx.xxx.xxx> status 502 (Connect Error <Connection refused/111>) for 'http://<origin-server-1.kabletown.net>/markt/1MB.out'```

Then I changed the drop_qstring.config to have the $p in it, and now i get:

```20150827.20h42m13s CONNECT: could not connect to <xxx.xxx.xxx.xxx> for 'http://<origin-server-1.kabletown.net>:80/markt/1MB.out' (setting last failure time)```

So, you see that the original port made it into the origin request in the second test. 

It is a problem that the first request didn't go to port 81, so I will enter that into the ATS queue.

**Comment by smalenfant** [comment]
Mark,

Have you fully restarted ATS? I know that traffic_line -x didn't take my
settings last time and caused some issues.
I also have a Mid-Cache

Here's what I got :
map http://edge01.cdn.kabletown.net/     http://origin:8081/
@plugin=header_rewrite.so @pparam=dscp/set_dscp_32.config
@plugin=regex_remap.so @pparam=drop_qstring.config
map http://cname.other.cdn.tld/     http://origin:8081/
@plugin=header_rewrite.so @pparam=dscp/set_dscp_32.config
@plugin=regex_remap.so @pparam=drop_qstring.config

drop_qstring.config
/([^?]+) $s://$t:$p/$1

[root@x]# curl http://edge01.cdn.kabletown.net/test -v
< HTTP/1.1 404 Not Found
< Server: ATS/5.3.1

The expected result was 404...

Edge-Cache log :
1440711316.060 chi=x.x.x.x phn=edge01.cdn.kabletown.net shn=origin url=
http://edge01.cdn.kabletown.net/test cqhm=GET cqhv=HTTP/1.1 pssc=404
ttms=96 b=168 sssc=404 sscl=168 cfsc=FIN pfsc=FIN crc=TCP_MISS
phr=PARENT_HIT uas="curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7
NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"

Mid-Cache log :
1440711316.048 chi=x.x.x.x phn=mid05.tld shn=origin url=
http://origin:8081/test cqhm=GET cqhv=HTTP/1.1 pssc=404 ttms=23 b=168
sssc=404 sscl=168 cfsc=FIN pfsc=FIN crc=TCP_MISS phr=DIRECT
uas="curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3
Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"

Not sure in the difference between your test and mine. Except that I got a
mid cache maybe?

Using trafficserver-5.3.0-570.a6f6a89.el6.x86_64

**Comment by mtorluemke** [comment]
Yeah, I restarted ATS between each config change.

**Comment by smalenfant** [comment]
So I've been testing the wrong remap today (wonder why the debug didn't work). Please discard previous emails.

Here's the difference between both using regex_remap debug, clearly shows the :8081 being added. Tried with/without parents and results are the same. 

Not sure why your and my results are different. 

With default drop_string :
```
[Aug 28 01:41:15.697] Server {0x2afa9fb76700} DIAG: (regex_remap) Target match string is `/test21'
[Aug 28 01:41:15.697] Server {0x2afa9fb76700} DIAG: (regex_remap) New URL is estimated to be 49 bytes long, or less
[Aug 28 01:41:15.697] Server {0x2afa9fb76700} DIAG: (regex_remap) New URL is http:/origin/test21 (length 42)
[Aug 28 01:41:15.697] Server {0x2afa9fb76700} DIAG: (regex_remap)     matched rule 1 [/([^?]+)]
```

Mid Cache :

```
1440726135.767 chi=68.1.14.33 phn=mid03.coxlab.net shn=origin url=http://origin/test21 cqhm=GET cqhv=HTTP/1.1 pssc=502 ttms=185116 b=247 sssc=000 sscl=0 cfsc=FIN pfsc=INTR crc=ERR_CONNECT_FAIL phr=DIRECT uas=curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
```

With modified drop_string :

```
[Aug 28 01:44:29.305] Server {0x2b451cc0b700} DIAG: (regex_remap) Target match string is `/test1'
[Aug 28 01:44:29.306] Server {0x2b451cc0b700} DIAG: (regex_remap) New URL is estimated to be 57 bytes long, or less
[Aug 28 01:44:29.306] Server {0x2b451cc0b700} DIAG: (regex_remap) New URL is http://origin:8081/test1 (length 46)
[Aug 28 01:44:29.306] Server {0x2b451cc0b700} DIAG: (regex_remap)     matched rule 1 [/([^?]+)]
```

Mid Cache

```
1440726269.309 chi=68.1.14.33 phn=mid03.coxlab.net shn=origin url=http://origin:8081/test1 cqhm=GET cqhv=HTTP/1.1 pssc=404 ttms=3 b=168 sssc=404 sscl=168 cfsc=FIN pfsc=FIN crc=TCP_REFRESH_MISS phr=DIRECT uas=curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
```

**Comment by mtorluemke** [comment]
Alright, good news! I can reproduce your result, but only if I use the header_rewrite plugin. It seems that when header_rewrite is in play, something is changing the original port to the origin port. Take header_rewrite out, and the original port remains as $p.

**Comment by mtorluemke** [comment]
Double-check this for me, and we'll close this PR. Then, between us we'll get the right issue filed with ATS.

**Comment by smalenfant** [comment]
Mark,

Confirmed. when header_rewrite is not present, the "request URL" Port is
added. Something is wonky.

Looks like this PR will not break anything when used with Traffic Ops
(since header_rewrite always used).

map     http://edge/     http://origin:8081/ @plugin=regex_remap.so
@pparam=drop_qstring.config :

[Aug 29 18:39:02.224] Server {0x2b1ef5e1d700} DIAG: (regex_remap) New URL
is http://origin:80/random2 (length 46)
[Aug 29 18:39:02.224] Server {0x2b1ef5e1d700} DIAG: (regex_remap)
matched rule 1 [/([^?]+)]

**Comment by mtorluemke** [comment]
Thanks. I'd rather see a PR for your idea of making this a parameter, than merge this one. That way, if/when we track down the weird interaction between regex_remap and header_rewrite, we don't have to scramble on the Traffic Ops side.

**Comment by smalenfant** [comment]
Sure. Will get with Hank to see if we can fix this with a database param.
Might need some help on making sure that new param makes it during
upgrade/installation.

**Pull request closed without merging**
