### PR TITLE
use $traffic_control.version for traffic_router version

### LINKED ISSUE #803: traffic_router rpm build does not get master version number
when building traffic_monitor rpm,  the version number on the rpm file name comes out 1.2.1 instead of the version number from traffic_control/VERSION

### PR DESCRIPTION
**Pull request by dangogh**
rpm will now be named from content of VERSION file.  This should be included in the 1.3.x release.

This fixes #803

### CODE REVIEW

**Comment by PSUdaemon** [comment]
This addresses #803?

**Comment by dangogh** [comment]
yes -- updated comment

**Comment by dangogh** [comment]
@trevorackerman please review latest change

**Comment by PSUdaemon** [comment]
@elsloo - Can you review this and merge if it looks good? I will merge the back port PR as long as you are +1 on this PR.

Thanks.

**Pull request merged**
