### PR TITLE
TO: allow user to delete parent cache and secondary cache entries

### LINKED ISSUE #1308: TO: Can't remove secondary_parent in cache group configuration
Version: 1.5.0RC0

I added secondary cache group for testing, although I don't have the proper ATS build installed. It makes ATS complains with `[Apr 15 13:05:21.628] Server {0x2b50019f4060} WARNING: [ParentSelection] Unknown modifier at line 5 in parent.config`.

Although, I believe I took the those out but the UI won't let you set `secondary_parent` back to `NO_PARENT`. When you do so, it copies the `parent cache group`. 

Also, the database seems to contain 2 different cache group id for primary and secondary, but the UI shows the same groups for both.

### LINKED ISSUE #1432: Ops: Failed to disassociate parent cachegroup from edge cachegroup
Reproduction Steps:
1. Add cache group "middle" from OPS, type=MID_LOC;
2.Add cache group "edge" from OPS, type=EDGE_LOC, Parent Cache Group = "middle"
3. Then tried to disassociate parent cache group from edge cache group. When choosing  'NO PARENT' from the 'parent cache group' drop list and save it. 'middle' appears again in  parent cache group
** (This issue also can be reproduced against secondary parent cachegroup)

### PR DESCRIPTION
**Pull request by xiaodzha**
Fixes #1432. Also Fixes #1308.

### CODE REVIEW

**Comment by knutsel** [comment]
Thanks @xiaodzha! Do we have a signed CLA from you? If not, would you mind sending a signed scan? See https://github.com/Comcast/traffic_control/blob/master/CONTRIBUTING.md 

Thanks!

**Comment by mitchell852** [comment]
i'm pretty sure @dangogh worked on the original code for this. i'll assign to him so he can look at the PR.

**Comment by dangogh** [comment]
This looks like the right fix to me -- I'm +1 on merging once we have the CLA..    Do we have it yet?

**Comment by dangogh** [comment]
@knutsel ^^

**Comment by dangogh** [comment]
@xiaodzha also please make the title be something more descriptive.  The "Fixed ..." comment should be in the description instead of the title..

Fixes #1432.  Also Fixes #1308.

**Comment by knutsel** [comment]
@dangogh: @xiaodzha is covered under the Cisco corperate CLA - ok to merge

**Pull request merged**
