### PR TITLE
Fixes #806

### LINKED ISSUE #806: TO: /api/{version}/asns.json has superfluous top-level key
```{
response: {
asns: [ ... ]
}
}```

should just be:

```{
response: [ ... ]
} ```

### PR DESCRIPTION
**Pull request by jheitz200**

### CODE REVIEW

**Comment by mtorluemke** [comment]
Even though this could be considered a 'bug' in the 1.1 API, I still think the new structure should only exist in version 1.2+ -- unknown how many folks are relying on the old structure.

**Comment by mitchell852** [comment]
make sure you update the docs

**Comment by mitchell852** [comment]
so really you don't need this anymore in the docs:

>lastUpdated

the > is used to show that the property is nested...and it no longer is now.

**Comment by jheitz200** [comment]
thanks for pointing that out

**Pull request merged**
