### PR TITLE
Documentation: correct spelling mistakes and minor grammar changes

### PR DESCRIPTION
**Pull request by rwhitworth**
Correcting spelling mistakes and minor grammar changes in the documentation.

### CODE REVIEW

**Comment by knutsel** [comment]
Hi Ryan - thanks for this PR. Do we have a signed CCLA on file from you? See https://github.com/Comcast/traffic_control/blob/master/CONTRIBUTING.md , we need that to be able to merge this.

**Comment by rwhitworth** [comment]
I expect it will be a few days before I am able to sign and return this document.  My employer is investigating signing a company-wide CCLA since we utilize this project and may have future contributions.  At that time I will be able to submit one as well.

**Comment by dneuman64** [comment]
Any updates on the CCLA?

**Comment by rwhitworth** [comment]
No response from legal at my company to the request.  I do not expect it is high priority. I'll close the PR for now and resubmit if the situation changes.

**Comment by dneuman64** [comment]
:(

**Comment by aaronsimms** [comment]
It's a priority to get this signed.  I just walked over and talked to our general counsel and she's going to get this signed.

**Pull request closed without merging**
