### PR TITLE
fix issue that the returned url is not right in NGB feature 

### PR DESCRIPTION
**Pull request by nbaoping**
fix issue #1673 that the returned url is not right when the relative redirect URL is set for NGB feature

### CODE REVIEW

**Comment by dneuman64** [comment]
Could you add a test for this, please?

**Comment by dneuman64** [comment]
@nbaoping are you able to get a test added to this so I can merge?  
Thanks,
Dave

**Comment by dneuman64** [comment]
@nbaoping:  This PR now has conflicts, can you please fix the conflicts so that I can merge?  
Thanks,
Dave

**Comment by mitchell852** [comment]
updates never made. we've moved to apache a long time ago.

**Pull request closed without merging**
