### PR TITLE
added force FAIL and OK for Netcool testing

### PR DESCRIPTION
**Pull request by hbeatty**
- traffic_ops_extensions.rst - updated cron examples
- traffic_ops_using.rst - added server checks table
- ToDSCPCheck.pl - updated example cron entries, incremented version,
added -f (force) -h (help) -q (quiet) options, checking command line
options failures prints help(), command line checks happen before any
work is done, added server status for syslog messages, quiet option
doesn’t post to Traffic Ops, added help()
- ToFQDNCheck.pl - updated example cron entries, updated version, added
-f (force) -h (help) -q (quiet) options, the quiet option doesn’t post
to Traffic Ops, updated help()
- ToORTCheck.pl - updated example cron entries, incremented version,
added -f (force) -q (quiet) options, quiet doesn’t post to Traffic Ops,
updated the ssh command to work better, server name for syslog messages
is not FQDN, added server status from TO and ORT version from edge to
syslog messages, updated help()
- ToPingCheck.pl - updated cron examples, incremented version, added -f
(force) -h (help) -q (quiet) options, moved $size up so that I can use
it in syslog messages, added server IPv4 address and size to syslog
messages, updated help()
- ToRTRCheck.pl - updated example cron entries, incremented version,
added -f (force) -h (help) -q quiet options, print help on command line
errors, changed server_assoc to hash, added server status from TO to
ccr_assoc hash, updated help()

### CODE REVIEW

**Comment by hbeatty** [comment]
I missed some of the OK and FAILs in the ToRTRCheck.pl. I'm working on adding those and will do another commit when complete.

**Comment by hbeatty** [comment]
Finished updating ToRTRCheck.pl

**Comment by knutsel** [comment]
@hbeatty, is this ready for review/merge now?

**Comment by hbeatty** [comment]
Yes. This is ready for review/merge.

**Comment by knutsel** [comment]
I think it would be better to use the /api/1.2 calls in stead of the /api/1.1 if this is going into master?

**Comment by hbeatty** [comment]
Yes. Will do. I'll updated and make another commit when ready.

**Comment by knutsel** [comment]
@hbeatty - I think this is still waiting from an update from you? If not, I'll merge as is, the 1.1/1.2 path is not that bigga deal.

**Comment by hbeatty** [comment]
@knutsel OH! If that is the case I'll fix the conflicts today and make a commit and then you can merge. I'm sure that I'll loop back around to this soon and I'll fix the 1.1/1.2 paths then.

**Comment by hbeatty** [comment]
@knutsel OK. Conflicts resolved and ready to merge. I'll work on fixing the API calls soon.

**Pull request merged**
