### PR TITLE
Traffic Router now accepts PKCS1 formatted certificates for https

### LINKED ISSUE #1850: Traffic Router should support pkcs1 and pkcs8 encoded private keys for SSL
Currently, TR only support PKCS8 encoded private keys.  Since TO creates private keys that are PKCS1 encoded TR should support both. 
When TR tries to load the keys that are currently created by TO is throws the following error:  `java.security.spec.invalidkeyspecexception: java.security.invalidkeyexception: ioexception : algid parse error, not a sequence `

### PR DESCRIPTION
**Pull request by trevorackerman**
Fixes #1850

### CODE REVIEW

**Comment by dneuman64** [comment]
It looks like we now ONLY support PKCS1 formatted private keys.  Is that the intention?

**Comment by trevorackerman** [comment]
Why do you believe it only supports PKCS1?

**Comment by dneuman64** [comment]
Looks like the cert eventually did get loaded

**Comment by trevorackerman** [comment]
Thanks for manually testing this.

The coordination of certificates between the Tomcat side handling connections and the traffic router webapp side is indeed wonky. I'm working on making this much better as I address #1851 

I can always work on solving #1851 first and then applying this fix afterwards. Either way is 👍  with me.

**Comment by dneuman64** [comment]
merged.  can you please cherry-pick this into the 1.7.x branch?

**Pull request merged**
