### PR TITLE
add dns_bypass_cname to deliveryservice

### PR DESCRIPTION
**Pull request by dangogh**

### CODE REVIEW

**Comment by elsloo** [comment]
45 characters seems a little short for the column size given the length of some domain names we would use with this feature. Maybe something like 128 characters instead?

**Comment by dangogh** [comment]
good point -- is length expected to be different from http_bypass_fqdn?

**Comment by mtorluemke** [comment]
nope -- using the same 255 should suffice.

**Comment by dangogh** [comment]
changed to 255

**Pull request merged**
