### PR TITLE
add fixes for #1385; mostly small tweaks

### PR DESCRIPTION
**Pull request by sradvan**
minor re-wording in a few places as well

building without errors for me now, with python-sphinx-1.2.3-4.fc23

for https://github.com/Comcast/traffic_control/issues/1385

Cheers,

### CODE REVIEW

**Comment by knutsel** [comment]
Hey thanks @sradvan! 

Do we have a signed CLA on file for you? If not, would you mind sending one? See https://github.com/Comcast/traffic_control/blob/master/CONTRIBUTING.md - there is a link to a pdf on that page.

**Comment by sradvan** [comment]
Hi @knutsel 

Where should I send the signed CLA? Thanks,

**Comment by knutsel** [comment]
If you could email a scan to me, that would be awesome!

**Comment by sradvan** [comment]
I've emailed it now

**Pull request merged**
