### PR TITLE
Multiple configuration file generation issues

### PR DESCRIPTION
**Pull request by smalenfant**
Commit contains all the issues attempting to fix. Please review carefully. There is enhancement and performance fixes (like MSO config).

This has been tested with a testbed similar to our production system, but please verify with your use cases.

Notes: 

- Before applying to a production system, make sure the delivery service has proper configuration for Query String Handling. Currently, the change only affects DS which has the QSH set to `use string in cache key, and pass up`.
- Origin Port. This has been running in production for a while, although it doesn't cover the case where the origin port is set on the URL. Fox example, don't set `http://example.com:80` as it won't work. Although I'm about 99% sure this didn't work either before. I'll be looking in fixing this in the future.

### CODE REVIEW

**Comment by mitchell852** [comment]
does this map back to any issues that are open?

**Comment by mitchell852** [comment]
oh wait. i can see in the commits this addresses #1478, #1203, #1278 and #1584

**Comment by dg4prez** [comment]
Tested and confirmed: these fixes appear to work as expected.

**Comment by mitchell852** [comment]
checked that duplicate parent.config entries are not created (#1278), qstring is set appropriately to "consider" (where qstring_ignore=0) (#1584), dest_domain and port are set in parent.conf appropriately based on ds.org_server_fqdn (port=80 if no port specified on ds.org_server_fqdn and port=x if port is specified) (#1203) and parent.config is generated in a reasonable timeframe (#1478). 

@dg4prez also tested and @dangogh blessed it with his Perl wand. once this is installed in our lab environment, regression testing will be required to ensure ATS functionality hasn't been affected in a negative way. merging...

**Pull request merged**
