### PR TITLE
Mso parent

### PR DESCRIPTION
**Pull request by dg4prez**
Compiles and runs, looks like there's a flaw in the logic - only the primary parent is getting added.

### CODE REVIEW

**Comment by dneuman64** [comment]
Is this meant to address #1814?

**Comment by dg4prez** [comment]
Yes

**Comment by dg4prez** [comment]
This is now tested and working in my lab system.  All origin servers in the DS are sorted by rank.  The ranked list is compared to the primary and secondary cache groups for the mid.  Origins in the ranked list in the primary cache group are written first in order of rank.  Secondary cache group is then written in order of rank, and finally origins without a cachegroup are written last.

**Comment by mitchell852** [comment]
have you performed any regression tests to ensure non-mso configurations are negatively affected by this change?

**Comment by dg4prez** [comment]
yes.  the work normally.

**Comment by dg4prez** [comment]
Went over this code and the changes with mtorluemke, who requested the parent_data scalar fixes to make them a little more clear.  I've also updated the documentation files.  I believe this is now ready to go.

**Comment by mitchell852** [comment]
i assigned this to @knutsel because he said he wanted to review it. i'll remove myself as an assignee.

**Comment by dangogh** [comment]
Code changes look good to me.... One little nit:  `docs/source/admin/quick_howto/muli_site.rst`

What's a `muli_site` ? :-)

**Comment by dg4prez** [comment]
Picky, picky.

**Pull request merged**
