### PR TITLE
Add Traffic Ops secure parameter

### PR DESCRIPTION
**Pull request by jifyang**
Can fix the issue #867: "Admin password visible to Operator User in TrafficOps UI".

The design document:
    https://docs.google.com/document/d/11urRVIs2qyTidAAUn-kYcHCPuLnMPZFmP5qrvDQYJZE/edit?usp=sharing

### CODE REVIEW

**Comment by mitchell852** [comment]
Can you run `db/admin.pl reverse_schema` to update the dbix files?

**Comment by jifyang** [comment]
The dbix file is updated. It is the file app/lib/Schema/Result/Parameter.pm.
I tested: after update to the newest code, this file should be same as the committed file in this pull request.

**Comment by dewrich** [comment]
@jifyang I verified that everything looks good for this feature, the only thing I had to fix is rename the migration because it's now out of sequence.  Please rename it to today's date and I'll merge this through

**Comment by dewrich** [comment]
@jifyang I also just noticed that there are no test cases, can you please add them?

**Comment by jifyang** [comment]
Updated for DB migration file name modification and test case.

**Pull request merged**
