### PR TITLE
Add RESTful API: get servers by profile

### LINKED ISSUE #1902: Add RESTful API: get servers by profile
The APIs document is at https://docs.google.com/document/d/13GjIizusc7iUZq7TuVrsp8JZ2eEx52xUtoX9uRNzFgc/edit?usp=sharing

3.10.5  Get servers by profile

### PR DESCRIPTION
**Pull request by jifyang**
Fixes #1902 
Document is at #1902

### CODE REVIEW

**Comment by mitchell852** [comment]
@jifyang - i reorganized the api routes and created a conflict for you. sorry, can you fix the conflict and put your new api routes in the proper section?

**Comment by jifyang** [comment]
Done. Thanks.

**Comment by mitchell852** [comment]
@jifyang - this existing api route already supports query parameters used to filter the server results:

`$r->get( "/api/$version/servers")`

for example:

api/1.2/servers?type=EDGE
api/1.2/servers?status=OFFLINE
api/1.2/servers?dsId=246

how about rather than creating a new api route (/api/$version/servers/profile/:profile_id) we just support a new profile query parameter like:

api/1.2/servers?profile=EDGE-FOO-BAR

see the section entitled "query parameters" in the [api guidelines](https://github.com/Comcast/traffic_control/wiki/Traffic-Ops-API-Guidelines-v1.x) where it talks about filtering which is what this is doing. thanks!

**Comment by mitchell852** [comment]
@jifyang - please make the suggested changes so we can get this PR merged before the move to Apache.

**Comment by jifyang** [comment]
@mitchell852 Sorry for late response because I am in holidays. Updated. Please help review.

**Comment by mitchell852** [comment]
created a PR for you to rename query param - https://github.com/jifyang/traffic_control/pull/3. when you merge that PR, it will update this PR.

**Comment by jifyang** [comment]
@mitchell852 Merged the PR. Thanks!

**Pull request merged**
