### PR TITLE
build all rpms -- round 2

### PR DESCRIPTION
**Pull request by dangogh**
I believe it's complete now based on the feedback provided in the previous PR #721.
  - All rpms build successfully with no environment vars required other than normal dev environment.
  - All subprojects get version from top-level VERSION file.
  - Each creates both a install rpm and src rpm (except traffic_monitor and traffic_router which build thru mvn).
  - traffic_ops_ort and traffic_ops are both built using the same script.
  - New subprojects are automatically included.
  - All subprojects built by default,  or specific ones provided as arguments to build/build.sh

### CODE REVIEW

**Comment by dangogh** [comment]
This fixes #507 -- exit status is now used consistently throughout all the build scripts.

**Comment by PSUdaemon** [comment]
This looks good.

If I attempt to build this, will it write anything outside of the build dirs?

**Comment by dangogh** [comment]
it writes only in rpmbuild and dist directories at the top level of traffic_control

**Comment by dangogh** [comment]
@PSUdaemon -- I've added a README.md as suggested..

**Comment by dangogh** [comment]
you're right -- carton is not needed until postinstall.   I'll remove that.

**Comment by PSUdaemon** [comment]
This looks good now, except there is a merge conflict. Can you rebase against master and I will merge?

**Comment by dangogh** [comment]
@PSUdaemon rebased with master...

**Pull request merged**
