### PR TITLE
Traffic Stats Spec file and documentation

### PR DESCRIPTION
**Pull request by dneuman64**
Updated the Spec file to copy the Grafana custom dashboard files into place as part of the RPM install process.
Updated the Traffic Stats admin docs to reflect the change.

### CODE REVIEW

**Comment by PSUdaemon** [comment]
You need to add an entry to the %files section for those files you copied as well.

**Comment by dneuman64** [comment]
good catch, @PSUdaemon

**Comment by smalenfant** [comment]
Should we had a dependency on grafana rpm to be installed?

**Comment by PSUdaemon** [comment]
@smalenfant I think that is a good idea, but in that case i think we should separate it out into two RPM's.

**Comment by dneuman64** [comment]
Adding it as a dependency is a good idea but we do not require grafana and traffic stats to be installed on the same server, so I do not think we should make it a dependency.  I put a comment in the docs that said if you put traffic stats and grafana on the same server then the files will be copied there for you, otherwise you need to do it yourself.

**Comment by PSUdaemon** [comment]
We can think about the 2 RPM's in the future if need be.

**Pull request merged**
